@betterthanvieshow_HostAddress = http://localhost:5041

### 會員註冊
POST {{betterthanvieshow_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "name": "測試用戶",
  "email": "test@example.com",
  "password": "SecurePass123"
}

###
